/**
 * 应用统一错误码枚举
 * 为所有业务异常提供语义化的错误代码，便于前端和日志分析
 */
export enum AppErrorCode {
  // 通用错误
  INTERNAL_ERROR = "INTERNAL_ERROR",
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // 授权/权限
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",

  // 速率限制
  AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED",

  // 资源不存在
  ORG_NOT_FOUND = "ORG_NOT_FOUND",
  PROPERTY_NOT_FOUND = "PROPERTY_NOT_FOUND",
  UNIT_NOT_FOUND = "UNIT_NOT_FOUND",
  TENANT_NOT_FOUND = "TENANT_NOT_FOUND",
  LEASE_NOT_FOUND = "LEASE_NOT_FOUND",
  PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // 唯一约束/冲突
  ORG_CODE_CONFLICT = "ORG_CODE_CONFLICT",
  PROPERTY_CODE_CONFLICT = "PROPERTY_CODE_CONFLICT",
  UNIT_NUMBER_CONFLICT = "UNIT_NUMBER_CONFLICT",
  TENANT_EMAIL_CONFLICT = "TENANT_EMAIL_CONFLICT",
  TENANT_PHONE_CONFLICT = "TENANT_PHONE_CONFLICT",
  USER_EMAIL_CONFLICT = "USER_EMAIL_CONFLICT",

  // 业务规则/关系
  CROSS_ORG_ACCESS = "CROSS_ORG_ACCESS",
  INVALID_RELATION = "INVALID_RELATION",

  // 租约激活相关
  LEASE_ALREADY_ACTIVE = "LEASE_ALREADY_ACTIVE",
  LEASE_STATUS_INVALID_FOR_ACTIVATION = "LEASE_STATUS_INVALID_FOR_ACTIVATION",
  UNIT_NOT_VACANT = "UNIT_NOT_VACANT",
  LEASE_ACTIVATION_CONFLICT = "LEASE_ACTIVATION_CONFLICT",

  // 支付单相关
  PAYMENT_STATUS_INVALID_FOR_MARK_PAID = "PAYMENT_STATUS_INVALID_FOR_MARK_PAID",
}
