/**
 * 审计事件类型枚举
 * 定义系统中所有可审计的操作类型
 */
export enum AuditAction {
  // 认证相关
  LOGIN = "LOGIN",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",

  // 租约相关
  LEASE_CREATED = "LEASE_CREATED",
  LEASE_ACTIVATED = "LEASE_ACTIVATED",
  LEASE_TERMINATED = "LEASE_TERMINATED",
  LEASE_UPDATED = "LEASE_UPDATED",
  LEASE_DELETED = "LEASE_DELETED",

  // 支付相关
  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_MARK_PAID = "PAYMENT_MARK_PAID",
  PAYMENT_UPDATED = "PAYMENT_UPDATED",
  PAYMENT_CANCELLED = "PAYMENT_CANCELLED",

  // 用户相关
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",

  // 组织相关
  ORGANIZATION_CREATED = "ORGANIZATION_CREATED",
  ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED",
  ORGANIZATION_DELETED = "ORGANIZATION_DELETED",

  // 房产相关
  PROPERTY_CREATED = "PROPERTY_CREATED",
  PROPERTY_UPDATED = "PROPERTY_UPDATED",
  PROPERTY_DELETED = "PROPERTY_DELETED",

  // 单元相关
  UNIT_CREATED = "UNIT_CREATED",
  UNIT_UPDATED = "UNIT_UPDATED",
  UNIT_DELETED = "UNIT_DELETED",

  // 租客相关
  TENANT_CREATED = "TENANT_CREATED",
  TENANT_UPDATED = "TENANT_UPDATED",
  TENANT_DELETED = "TENANT_DELETED",
}

/**
 * 实体类型枚举
 * 定义系统中所有可审计的实体类型
 */
export enum AuditEntity {
  USER = "USER",
  ORGANIZATION = "ORGANIZATION",
  PROPERTY = "PROPERTY",
  UNIT = "UNIT",
  TENANT = "TENANT",
  LEASE = "LEASE",
  PAYMENT = "PAYMENT",
}
